// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "yNF7Dpfm9gNgv1NG9vP2e0eeNfMd1RM3sPBSjEzXcPbQpDYLmSwT4gT1cKoZAinX1Ctuf4";
}
}
}

